### ISSUE TITLE
Spam of Failed to buffer metrics data for $CriticalTime after $10 attempts messages

### ISSUE THREAD

**Issue by robbaman** [Particular/NServiceBus.Metrics.ServiceControl#124]
We're running multiple endpoints in a docker environment with similar settings. Regularly one of those goes on fritz and uses 100% available CPU. When checking the logs via `docker container logs --tail 100 <name>` the log is completely filled with thousands of these messages:

```
2020-10-08 09:25:54.725 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.725 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.725 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.725 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.726 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.727 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.728 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.729 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.729 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.729 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
2020-10-08 09:25:54.729 WARN  Failed to buffer metrics data for $CriticalTime after $10 attempts.
```

What process is responsible for generating this message (so I can perhaps deduct what's different between this particular service and the others that are seemingly similarly configured)? Any help resolving this would be appreciated.

Thanks

**Comment by robbaman** [comment]
Hi @lailabougria, apologies for putting this in the wrong place, thanks for setting that right.

It's always the same endpoint, but from a configuration point of view this endpoint is not much different than any other as we use the same base-template for all our services.

One thing I realized later that might be related in some way is that this service is used to perform various low priority tasks and as such it is regularly bombed by things like logging requests that may result in a queue of several thousand items. 

While this also happens in our production environment (where we don't see the buffer metrics error), but in my development docker environment for some reason it seems that NServiceBus picks up 36 messages at a time in the default configuration. I couldn't tell you if this is related, but in our production environment it only does 12 concurrent messages. 

Perhaps that there is some sort of race condition that occurs when this many messages are picked up at the same time.

Hope that helps.

**Comment by lailabougria** [comment]
Hi @robbaman, don't worry about misplacing the issue, it's hard to keep track 😄 

About the concurrent processing, there's an explanation for that: if there's no value configured, which I'm assuming is the case in your development environment (or even in your production environment as well), the framework decides the number of concurrent messages to process according to the number of cores available on the machine hosting the endpoint. We have [some documentation](https://docs.particular.net/nservicebus/operations/tuning) around this.

In order to keep the memory pressure low, we're making use of a ring buffer to optimize the metrics collection. If the endpoint fails to deliver the metrics to the ServiceControl monitoring instance, the buffer overflows, which is why you're seeing the logging messages appear. Could it be the case the ServiceControl monitoring instance is not running / available / misconfigure on the environment in which you see these logs?

**Comment by robbaman** [comment]
> Could it be the case the ServiceControl monitoring instance is not running / available / misconfigure on the environment in which you see these logs?

This could be, it's my development machine which has RabbitMQ running locally in a docker container which regularly hasn't started yet when the ServiceControl services are starting up. This causes them to fail to start (which is something unrelated I'd love for you to fix). 

But firstly, if this is the issue you'd think this happens to all the services running on my local machine which is not the case (except perhaps that this service as mentioned regularly has a higher number of queued messages during startup)

And secondly, I assume the communication with ServiceControl monitoring is done via the queue. It shouldn't matter if ServiceControl is actually running or not should it?

**Comment by lailabougria** [comment]
Would you mind sharing your endpoint configuration privately through support-at-particular-dot-net so that we can look into the problem with a little bit more detail? Thanks in advance!

**Comment by robbaman** [comment]
Sure, are you referring to the configuration.txt file in the .diagnostics directory?

**Comment by lailabougria** [comment]
Yes, both the configuration file and the code you have to configure the endpoint would come in handy 👍

**Comment by robbaman** [comment]
I'm looking at how best to get this code in a readable fashion so please bear with me. We've got some stuff pushed away in NuGet packages of our own to standardize the configuration of all our service.

I've tried to add this to our configuration, but it doesn't seem to do anything though:

`endpointConfiguration.LimitMessageProcessingConcurrencyTo(2);`

As soon as I start the endpoint the RabbitMQ management portal shows 36 unacked messages in progress. I would expect this to be just 2 when the messageprocessing is limited to 2.

**Comment by danielmarbach** [comment]
@robbaman @timbussmann has [published a new release](https://discuss.particular.net/t/nservicebus-metrics-servicecontrol-3-0-5-patch-release-available/2211) that should fix this problem. Please give 3.0.5 a spin

**Comment by robbaman** [comment]
I was just in the process of composing an email stating the error persists with some attached logs. This mail should arrive momentarily.

**Comment by danielmarbach** [comment]
@robbaman @timbussmann @seanfarmar and I are on it. Sorry that you are still in this situation. In our test environments it significantly improved the situation and even made it disappear. I hear Tim is already in contact with you to exchange more logging information. I'll sync with him to see what we can do

**Comment by danielmarbach** [comment]
We have released [another patch](https://discuss.particular.net/t/nservicebus-metrics-servicecontrol-3-0-6-patch-release-available/2217) and think we have finally fixed it. Thanks for the patience.

**Comment by robbaman** [comment]
Let me just use this place to publicly applaud the awesomeness of Particular for their diligence, patience and persistence in helping me solve this issue. It looks to me like it was one of those fringe cases that are often hard to reproduce and debug, but at all times they've been very thorough and I can confirm that version 3.0.6 of the NuGet package solve this problem for me.

Thanks again Particular Team!

**Comment by timbussmann** [comment]
thank you very much for your kind words @robbaman! We are happy to hear that this issue is finally resolved :)
